name: "1-TIME: Key Generator"

on:
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore dashing.keystore -alias dashing-alias -keyalg RSA -keysize 2048 -validity 10000 -storepass "dashing2026" -keypass "dashing2026" -dname "CN=Dashing into Neo, OU=Game, O=AwiquarGame, L=Unknown, ST=Unknown, C=ES"
          
      - name: Output Base64 for GitHub Secrets
        run: |
          echo "------------------------------------------------------------"
          echo "COPIA TODO EL TEXTO DE ABAJO Y PÉGALO EN EL SECRETO 'SIGNING_KEY':"
          echo "------------------------------------------------------------"
          base64 -w 0 dashing.keystore
          echo ""
          echo "------------------------------------------------------------"

      - name: Upload Keystore File (GUARDAR ESTO EN TU PC)
        uses: actions/upload-artifact@v4
        with:
          name: dashing-keystore-FILE
          path: dashing.keystore
